### DISCUSSION TITLE
How to change Patternfly default colours

### DISCUSSION THREAD

**Discussion by gabrielefronze** [cockpit-project/cockpit#16256] [Q&A] [answered]
Hello good people!

Thank you for the great tool cockpit is, I really am in love with it and I'm spreading the word with colleagues and friends.

I am on the way to customise it in order to (graphically) integrate it with an ecosystem I am working on and I would like to get some tips on how to override the default UI colours (mainly the blue/dark blue ones).

As far as I understand these should be the ones defined by Patternfly, but I cannot find where to override them.
I tried editing the file affected by [this commit](https://github.com/Elemento-Modular-Cloud/cockpit/commit/f66ae41ee76dbf28eea7ece6f4894255c7b2645e), but without success.

Can you give me some hints?

Thank you very much,

Gabriele

**Comment by garrett** [comment]
The file you linked is intended to override PatternFly 3 only, to make it resemble PatternFly 4. Much of Cockpit has been ported over to PatternFly 4, so editing that file will have no effect on anything that's in PatternFly 4.

Which colors in particular are you trying to change? Most are represented in CSS variables these days, not just for PatternFly 4, but also for PatternFly 3 and Cockpit custom widgets.

There's one exception: The stripe at the top of the page. That's an accent color tied to the machine it's on, to help you differentiate between multiple machines (if you're using multiple machines). It's blue by default and a custom color can be set when adding or editing machines in the host switcher.

**Reply by garrett** [reply]
If you're recompiling Cockpit yourself, I'd suggest looking into redefining some of the CSS variables, most likely in `page.scss`.

If you just want to change the blue of the links and buttons, you'd probably get pretty far redefining these variables in `:root`:

```scss
:root {
  --pf-global--link--Color: #06c;
  --pf-global--link--Color--hover: #004080;
  --pf-global--link--Color--visited: #40199a;
  --pf-global--primary-color--100: #06c;
  --pf-global--primary-color--200: #004080;
}
```

(The colors included above are the default ones.)

There are a ton more colors too, and you can play around with them in the DOM in any web browser inspector. Changing them in the dev tools should propagate to the page, and for browsers which show changes made in the dev tools, like Firefox, you can then copy them back to whatever file you might be editing.

**Reply by gabrielefronze** [reply]
Dear Garret,

Thanks for the heads up!
Ultimately, while waiting for your reply, I tried overriding some CSS values as you suggested, with mixed success.

I'll share with you my findings later on.

While I sill need some help with a pair of overrides not working (I don't get why), I reverse engineered a bunch of them which can be overridden from the branding CSS itself. I would be more than glad to add such information in the branding guide.

Cheers

**Reply by garrett** [reply]
There's also an initiative within PatternFly to handle theming, mainly focusing on a dark mode theme, but also with the secondary intention to reskin the look of PatternFly. However, it isn't ready for use — and it would take some time and effort before it would work in Cockpit, as we're still not 100% PatternFly 4 yet.

(Sorry it took a while to respond. I was on vacation and the others on the team usually don't get into these details about the color and CSS variables and such, as they (rightfully) don't need to. Glad you mostly figured it out in the meantime though!)

Updating the branding guide with these tweaks would be a great idea!

**Comment by gabrielefronze** [comment]
Hey there,
I'm getting back after putting on an instance of cockpit from my own fork.
Right now I am enforcing my own branding by replacing the `default` branding with the one I modified myself.
I also needed to modify the `page.scss` file, as @Garrett suggested. Here a snippet of the `:root` override I came out with:

```css
:root {
    --ct-color-host-accent: #FFA601 !important;
    --ct-color-list-hover-text: #FFA601 !important;
    
    /* Theme color */
    --pf-global--primary-color--100: #fdc55d !important;
    --pf-global--primary-color--200: #FFA601 !important;
    --pf-global--warning-color--100: #eea0d3 !important;
    --pf-global--warning-color--200: #D35FAA !important;

    /*  Link colors */
    --pf-global--link--Color: #FFA601 !important;
    --pf-global--link--Color--hover: #fdc55d !important;

    /*  Inline link colors */
    --pf-c-button--m-link--Color: #FFA601 !important;
    --pf-c-button--m-link--m-inline--hover--Color: #fdc55d !important;

    /*  Nav link colors */
    --pf-c-badge--m-unread--BackgroundColor: #FFA601 !important;
    --pf-c-nav__link--Color: #FFA601 !important;
    --pf-c-nav__link--m-current--Color: #fdc55d !important;
    --pf-c-nav__link--before--BorderColor: #FFA601 !important;
    --pf-c-nav__section__link--hover--after--BorderColor: #fdc55d !important;

    /*  Progress indicators colors */
    --pf-c-progress__indicator--BackgroundColor: #FFA601 !important;
    --pf-c-progress__bar--BackgroundColor: #fadda7 !important;

    /*  Table headings colors */
    --pf-c-table__sort__button__text--Color: #FFA601 !important;
}
```

Here are some screenshots of the results so far.

<img width="1502" alt="image" src="https://user-images.githubusercontent.com/5606511/133263213-97961866-379d-4669-b2a7-61b77c2c55cc.png">

<img width="1502" alt="image" src="https://user-images.githubusercontent.com/5606511/133263270-fb7b9878-3e3e-4c9a-8e3e-9bcb05edf979.png">

<img width="1502" alt="image" src="https://user-images.githubusercontent.com/5606511/133263369-31e4f88d-cf20-49c2-83c1-d942edaa4e50.png">

I am still trying to override the chart colours.
The only thing I don't really like is acting directly on the `page.scss` file to override the `:root` section.
I would rather prefer to be able to do the same via the `branding.css` instead.
