### ISSUE TITLE
User auth dialog add key dropdown is cut off due to overflow

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#10424]
The auth dialog from the user menu (in the top-right of Cockpit) has `overflow: auto` set. As the dropdown is contained within the overflow region, it pops down and makes the space scrollable.

There are a few ways to fix this problem:

1. A proper solution would be to remove the `modal-scrollable` class from the dialog and set a max-height and overflow for the list. _However_, the entire contents of the dialog is a list, and `tbody`s do not accept max-height or overflow. As a result, we cannot use this solution without reworking all the code.

2. Another fix would be to remove `modal-scrollable` only when the dropdown appears. But then the height could vary wildly and might even also cause the dialog to go offscreen in some cases.

3. Move the dropdown to outside the scrollable area. But then JavaScript needs to calculate coordinates, move the dropdown to the right location, and track & update on window resize events. Also not good.

4. A "simple" workaround would be to add a min-height that is larger than the dropdown + everything above it. However, the dialog would be weirdly empty.

After poking around a bit, I don't really see a straightforward fix. Everything but the first solution would have a bunch of side-effects and add fragility.

**Comment by garrett** [comment]
I'm sure this kind of bug is not limited to this specific dialog. This could happen anywhere custom dropdowns in dialogs might happen, especially with areas which may get larger.

In most other cases, we could have the dropdown inside a non-scrolling dialog and just scroll the list if it gets too tall. (In this case, we need to split it up so that's possible. That's solution number 1.)

**Comment by garrett** [comment]
Solution 5:

Change `.dropdown-menu` so that it uses fixed position & adjust its placement in a relative manner:

```css
/* This is additional CSS that needs to be included. */
.dropdown-menu {
  margin-top: 25px;  /* Height of the input + borders - 1 so it overlaps the border */
  left: 31px; /* Dialog padding to the left of the input + 1px border of the input */
  right: 69px; /* Dialog padding + button + horizontal borders for button + space between button and input + border of input */
  max-height: 50vh; /* Max-height can be whatever... here, it's ½ the screen height. */
}
```

All of the above are given in pixel values. The right value, in particular, might be problematic in different languages as the button's width could vary. The rest should be fairly consistent, but it feels dirty to use pixel values in all these cases.

This seems to work in testing. I haven't triggered the overflow however.
