### ISSUE TITLE
CSP errors while loading fonts with inlined CSS

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#11366]
Reported by @piiiggg in https://github.com/cockpit-project/cockpit/issues/11346:

The network page has inline CSS in the `<style>` tag within the HTML of the page. In the CSS, it attempts to load fonts with the following lines:

```css
@font-face{font-family:'Open Sans';font-style:normal;font-weight:400;src:url(cockpit/static/fonts/OpenSans-Regular-webfont.woff) format('woff')}
@font-face{font-family:'Open Sans';font-style:normal;font-weight:700;src:url(cockpit/static/fonts/OpenSans-Bold-webfont.woff) format('woff')}
```

CSP prevents loading resources from inline CSS.

Thankfully, this isn't a huge issue, as the fonts are loaded elsewhere. But attempting to load fonts from the inline CSS should be fixed.
