### ISSUE TITLE
Button groups break in narrow widths

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#11601]
Button groups break in narrow widths:

![thumb0034](https://user-images.githubusercontent.com/10246/56121509-8f7fbd00-5f70-11e9-9be7-702abc1e0dd9.jpg)

Solution seems to be to add:
```css
.btn-group, .btn-group-vertical {
  display: inline-flex;
}
```

Switching to ct-form-layout would also help with the layout in Services details:

![Screen Shot 2019-04-15 at 11 24 41](https://user-images.githubusercontent.com/10246/56121767-25b3e300-5f71-11e9-82f9-81d9269c7c2d.png)
