### ISSUE TITLE
On Off Switch: Emulate native focus rings

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#11826]
Here's a snippet of CSS that should be added to the switch LESS file to use a Chrome & Safari style blue ring except on Firefox, where it uses the dotted outline.

(LESS lets us nest like this, and it sorts it out.)

```less
  :focus ~ .switch-toggle::before {
    /* Approximate Chrome's focus ring */
    border: 2px solid rgba(0, 98, 220, 0.4);
    
    @-moz-document url-prefix() {
      /* Approximate Firefox's focus ring */
      border: 1px dotted rgba(0, 0, 0, 0.75);
    }
  }
```

See it in action at https://codepen.io/garrett/pen/MRZYaV — be sure to use various browsers.

Click on a heading and hit tab.

This should help address https://github.com/cockpit-project/cockpit/pull/11769#issuecomment-492254728 — I just need to turn it into a PR. :wink:
