### ISSUE TITLE
Improve firewalld in order to create rules based on pure ports without making anonymous services

### ISSUE THREAD

**Issue by michaelsogos** [cockpit-project/cockpit#13189]
Hi,

In case, we use `firewall-cmd --permanent --zone=public --add-port=8080/tcp` it will not be shown in firewall page under network.

Seems that actually cockpit show only "services".

Here an example of which ports are manually opened and not shown by cockpit UI.
```
  target: default
  icmp-block-inversion: no
  interfaces: ens160
  sources:
  services: ssh dhcpv6-client
  ports: 9090/tcp 80/tcp 8083/tcp 8082/tcp 8081/tcp 8080/tcp
  protocols:  
  masquerade: no  
  forward-ports:  
  source-ports:  
  icmp-blocks:  
  rich rules:  
```

It will be a great if cockpit can show and configure just ports and not only services 😄 .
