### ISSUE TITLE
mobile: Notifications in mobile mode are suboptimal

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#14106]
As pointed out by @marusak @ https://github.com/cockpit-project/cockpit/pull/13482#issuecomment-624626261:
![Screen Shot 2020-05-06 at 14 40 46](https://user-images.githubusercontent.com/12330670/81177985-cbd0f180-8fa7-11ea-9e50-5667b6dd6737.png)

**Comment by garrett** [comment]
Fix is to redo the layout for mobile:

```scss
@media (max-width: $screen) {
  .pf-c-alert {
    grid-template-areas: "icon title" ". content" ". action";
    grid-gap: var(--pf-global--spacer--sm) 0;
  }
}
```

It changes the alert to look like this:

![Screen Shot 2020-05-18 at 17 03 12](https://user-images.githubusercontent.com/10246/82228513-80183380-9929-11ea-8e7d-b15cd09aae16.png)

...but: In PF4, most alerts have an action area of an × icon, and that should be in the top-right. As our sudo prompt is using a button action instead of an ×, it should be handled differently. (See the issue with the above CSS in the MOTD alert.)

This means we'll want to probably handle this either as a one-off, or suggest PatternFly to have two different modes (for a dismissable action versus one that's not dismissable, but has an action button instead).

Right now, PatternFly doesn't differentiate the action types — either in the alert's top-level element or even in the action class. So we'd have to have a `ct-m-alert-action` class we'd apply, I suppose. And/or ask PF to add something similar.
