### ISSUE TITLE
Port log detail table to PF4

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#15170]
Page: Logs / detail view (click on a log entry)

The page uses an HTML table with "info-table-ct" and the "labels" are actually `<td>`s instead of `<th>`s, making this inaccessible.

We _could_ fix the table... or outright port it to PF4 (which should also fix the a11y issues). Of course, it makes sense to do the latter and port to [PF4's description list (horizontal variant)](https://www.patternfly.org/v4/components/description-list#horizontal).

---

Once this is done, we might want to consider de-emphasizing the **ALL_UPPERCASE** labels, perhaps with CSS like the following:

```scss
.log-details .pf-c-description-list__term {
  --pf-c-description-list__term--FontWeight: var(--pf-global--FontWeight--normal);
  color: var(--pf-global--Color--200);
}
```

PF4's bolded labels in the description list wasn't designed with the intent of having all description list terms to be uppercase. They're yelling.

In a previous commit a while back, I wanted to to make these lowercase (via CSS, so copy/paste would preserve the uppercase), but was told that it's important to maintain parity with journalctl's commandline. (Is it actually case-sensitive though?) So we'd have to figure out another way to de-emhpasize the characters.

Our main font, RedHatText does not support tabular numbers, so I'd be surprised if it would support a small capitals option. Therefore, I am suggesting the above snippet (or something like it) as a one-off.
