### ISSUE TITLE
Form elements are misaligned

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#15362]
Here's an example from the Create VM dialog:

It currently looks like this:
![Screenshot_2021-02-17 PatternFly 4 • Form(3)](https://user-images.githubusercontent.com/10246/108230960-94e85880-7141-11eb-9e73-37c233ffdca6.png)

It should look like this (aligned by shifting pixels around in GIMP):

![Screenshot_2021-02-17 Virtual Machines - garrett Rain(2)-aligned](https://user-images.githubusercontent.com/10246/108231052-aaf61900-7141-11eb-8ace-4e7dfc5b1df9.png)

Here's the difference of the two images, inverted:
![Screenshot_2021-02-17 Virtual Machines - garrett Rain(2)-difference](https://user-images.githubusercontent.com/10246/108231104-b77a7180-7141-11eb-8151-e57811e64158.png)

As there's some PF3 overriding browser defaults which steps on PF4's assumptions, I also copy/pasted the HTML as constructed in the DOM to the PatternFly website (sliders are wrong as we're still using overridden PF3 sliders, as PF4 just recently introduced sliders):

![Screenshot_2021-02-17 PatternFly 4 • Form(3)](https://user-images.githubusercontent.com/10246/108231567-2eb00580-7142-11eb-92bf-017235da59e9.png)

In the copy/paste, you can see the radios for system/session are still very wrong, the labels are still offset incorrectly (by two pixels off baseline), and the checks and radios are still misaligned to their respective labels (although aligned to bottom instead).

**Comment by garrett** [comment]
With the following override, I have fixed the radios and checks relative to their own labels (not the placement of the form labels):

 ```scss
// PF assumes check sizes are Chrome-based; size needs to be set for cross-browser compatibility
.pf-c-check > .pf-c-check__input {
    // Set the height of the input widget to be the same as its label
    --pf-c-check__input--Height: var(--pf-c-check__label--FontSize);
    // Offset by the top half of the difference between the height and the line height
    --pf-c-check__input--MarginTop: calc((var(--pf-c-check__label--LineHeight) - 1) / 2 * var(--pf-c-check__input--Height));
    // PF3 sets a margin which messes with PF4, so set PF4's rule again here
    margin-top: var(--pf-c-check__input--MarginTop);
}

// PF assumes radio sizes are Chrome-based; size needs to be set for cross-browser compatibility
.pf-c-radio > .pf-c-radio__input {
    // Set the height of the input widget to be the same as its label
    --pf-c-radio__input--Height: var(--pf-c-radio__label--FontSize);
    // Offset by the top half of the difference between the height and the line height
    --pf-c-radio__input--MarginTop: calc((var(--pf-c-radio__label--LineHeight) - 1) / 2 * var(--pf-c-radio__input--Height));
    // PF3 sets a margin which messes with PF4, so set PF4's rule again here
    margin-top: var(--pf-c-radio__input--MarginTop);
}
```

And it looks like this:

Firefox|Chrome|WebKit
--|--|--
![Screenshot from 2021-02-17 17-26-48](https://user-images.githubusercontent.com/10246/108234774-6b313080-7145-11eb-8934-cb32d84bb9c3.png)|![Screenshot from 2021-02-17 17-27-09](https://user-images.githubusercontent.com/10246/108234764-6a000380-7145-11eb-9d25-854aa94a46cb.png)|![Screenshot from 2021-02-17 17-26-55](https://user-images.githubusercontent.com/10246/108234772-6b313080-7145-11eb-82b0-5c3f429c9212.png)

...all are properly aligned. Amd this was tested on other pages as well. I needed to redefine the top margin here again to what PF4 does to undo the PF3 blanket setting for all radio/check inputs.
