### ISSUE TITLE
login: Block on lack of :where() and :is() support.

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#16990]
Browsers have added support for `:is()` and `:where()` a bit over 2 (Firefox, Safari) to 1 (Chrome, et al) years ago. PatternFly, in the latest release 4.171.1 started using `:where()` (in 2 places).

As using `:is()` or `:where()` _will_ definitely break the UI where it is used, we need to block the old, out of date, insecure browsers that do not support this CSS.

This will need to be added as a supports check on the login page — and the website needs to check for this too, with its browser compatibility pass/fail and browser version estimates.

**Comment by garrett** [comment]
This blocks https://github.com/cockpit-project/cockpit/pull/16967 from landing.

Right now, PF's usage doesn't completely break the UI of the site (but it will make parts look sloppy). However, if they're going for it (and they have), then that means it's inevitable that it will definitely break things if we let a browser through that doesn't support this CSS.

Thankfully, all browsers — including Firefox Extended Service Release and all versions of Safari on iPhones from 6 onward (released in 2015 and have the latest iOS) will support this, so we really shouldn't be blocking any reasonably updated browser.

**Comment by garrett** [comment]
Demo of how `:is()` and `:where()` are used:

Here's some CSS with a line that doesn't use `:is()` or `:where()` by one that follows that is fully equivalent:

```css
.header li, .header a {
  background: red;
}

.header :is(li, a) {
  background: blue;
}

.header li, .header a, .footer li, .footer a {
  background: green;
}

:is(.header, .footer) :is(li, a) {
  background: green;
}
```

(`:is()` adds specificity; `:where()` is the same, except it doesn't add specificity.)

Here's a comparison of what this looks like in SCSS (this is what I wrote to generate the above example):

```scss
.header {
  li, a {
    background: red;
  }
}

.header {
  :is(li, a) {
    background: blue;
  }
}

.header, .footer {
  li, a {
    background: green;
  }
}

:is(.header, .footer) {
  :is(li, a) {
    background: green;
  }
}
```

So the resulting difference is that wrapping things in an :is() instead of compiling out to the full string makes it so that there's just one matcher for CSS instead of multiple.

It's probably easier to visualize if I re-paste the CSS block and add extra returns on each selector:

```css
.header li,
.header a {
  background: red;
}

.header :is(li, a) {
  background: blue;
}

.header li,
.header a,
.footer li,
.footer a {
  background: green;
}

:is(.header, .footer) :is(li, a) {
  background: green;
}
```

So, as you can see, if a browser doesn't support `:is()` and `:were()`, this will easily break the site, especially once PF uses the selectors more.

**Comment by garrett** [comment]
Note: I didn't include a `:where()` example, as there's no equivalent in SASS or CSS, as it doesn't change specificity. It's basically like `:is()` without becoming more specific. This is why PF is using `:where()` in places now.

This equates to removing extra selectors to be more specific (including IDs or more nesting or overly specific class chaining) or, in some cases, having to use `!important`.

**Comment by garrett** [comment]
Here's a test for `@supports`:

```css
@supports selector(query) {
  body {
    background: green;
  }
}

@supports selector(:is():where()) {
  body {
    background: purple;
  }
}

@supports selector(:where(:valid, :unsupported)) {
  body {
    background: gold;
  }
}
```
See it at https://codepen.io/garrett/pen/GROOQNV

Relevant features to check:
https://caniuse.com/mdn-css_at-rules_supports_selector
https://caniuse.com/mdn-css_selectors_where
https://caniuse.com/mdn-css_selectors_where_forgiving_selector_list

We need to use the `@supports selector() {}`, which was supported before `:where()` and `:is()`.

However, we cannot check for, nor use, `:where()` and `:is()` with forgiving selector list yet, as WebKit doesn't support that yet, sadly. https://developer.mozilla.org/en-US/docs/Web/CSS/:where#forgiving_selector_parsing

HOWEVER, I did test it in GNOME Web and it works, so now I'm suspicious of Safari's supposed lack of support. I think caniuse/MDN might be wrong here?
