### ISSUE TITLE
Network/Firewall: sort services in zones in alphabetical order

### ISSUE THREAD

**Issue by paoloteti** [cockpit-project/cockpit#18825]
When displaying zones using `sudo firewall-cmd --list-all-zones` , services are alphabetically sorted. 
As example:

```
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: eno1 ens4f0np0
  sources:
  services: cockpit dhcpv6-client docker-registry docker-swarm ssh
```
Instead firewall page, lists services in the order their have been added. In the same server I see `ssh dhcpv6-client cockpit docker-swarm docker-registry` on cockpit.

It would be useful and convenient to rearrange the table in alphabetical order.
