### ISSUE TITLE
Terminal height is too small

### ISSUE THREAD

**Issue by qooob** [cockpit-project/cockpit#2517]
Guys, hi!

I have made a small fix that makes the terminal look like this:

![screenshot from 2015-07-29 12-52-07](https://cloud.githubusercontent.com/assets/4426533/8954792/aa72b1a6-35f0-11e5-8e34-acc7a7ccfce2.png)

Here is the both CSS and JS that you could add to the bundle to make things work. Notice it will require to make some changes to the Terminal so inner part of it will also stretch:

```CSS
.panel.panel-default.console-container { 
	width: 98%;
	width: 98.6%;
	}
 
#terminal.console > .terminal {
     width: 100%;
     height: 100%;
}
```

```JS

function setTerminalHeight() {
	if ($('#terminal.console').length) {
          $('#terminal.console > .terminal').css('height', parseInt(window.parent.$('.container-frame').css('height')) - 75);
     }
}

$(window).on('load, resize', function(){
      setTerminalHeight();
});

```

Will you fix it? Because now it super annoying?
