### ISSUE TITLE
How to make cockpit contact kubernetes API server using http instead of https

### ISSUE THREAD

**Issue by praoreo** [cockpit-project/cockpit#5039]
Hi,

In my lab setup API server is running at the following path

```
curl http://XXX.XXX.XX.X:8080/api
{
  "kind": "APIVersions",
  "versions": [
    "v1"
  ],
```
I could start cockpit-kubernetes dashboard as a docker container and I passed KUBERNETES_SERVICE_HOST, KUBERNETES_SERVICE_PORT env variables correctly. 

`
docker run --env-file=test.env --net=host --rm -it cockpit/kubernetes:latest`

Cockpit dashboard is accessible at https://XXX.XX.XX.X:9090. However cockpit is not able to talk to API server as it's trying to contact API server using https instead of http.

`
2016/09/12 16:01:15 Negotiate failed: Couldn't connect to the api: Get https://XXX.XXX.XX.X:8080/api: tls: oversized record received with length 20527`

How can I make cockpit contact API server using http instead of https?

**Comment by petervo** [comment]
This isn't supported by the cockpit/kubernetes image at the moment. I'd suggest running with a self-signed certificate and using KUBERNETES_INSECURE, skip certificate verification.

**Comment by praoreo** [comment]
@petervo 
I tried to set KUBERNETES_INSECURE=true in env file and after that also cockpit is contacting API server using https. Am I missing anything here?

```
root@tbserver3:/etc/default# docker exec -it bbe85b0f9f23 bash
[root@tbserver3 /]# env
KUBERNETES_INSECURE=true

```

`2016/09/12 18:05:12 Negotiate failed: Couldn't connect to the api: Get https://XXX.XXX.XX.X:8080/api: tls: oversized record received with length 20527`

**Comment by petervo** [comment]
Like i said above, the cockpit/kubernetes image only supports talking to the kubernetes API server over https. The is no http only support. You will need to run your api server with a self-signed certificate to be able to use it with the cockpit/kubernetes container.

**Comment by praoreo** [comment]
@petervo 
Thanks for the inputs. I could bring up my setup using a self-signed certificate. 
But I am not able to login to kubernetes/cockpit dashboard. I tried the login mentioned in ~/.kube/config but that didnt work. Server login also didn't work. 

Every time I get the below error.

```

2016/09/13 21:15:48 Couldn't get api version: 401 Unauthorized
2016/09/13 21:15:50 Couldn't get api version: 401 Unauthorized
```


Could you please guide what login cockpit uses to login to the dashboard? I am running cockpit as a docker container

`docker run --env-file=test.env --net=host --rm -it cockpit/kubernetes:latest`

```
root@tbserver3:/home/tbserver3# kubectl config view
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://XXX.XX.XX.X:8081
  name: ubuntu
contexts:
- context:
    cluster: ubuntu
    user: ubuntu
  name: ubuntu
current-context: ubuntu
kind: Config
preferences: {}
users:
- name: ubuntu
  user:
    password: 98Ri4cxKlQ0tbpWR
    username: admin

``
```
