### ISSUE TITLE
Registry: image stream created missing section in yaml

### ISSUE THREAD

**Issue by thomasmckay** [cockpit-project/cockpit#5117]
I created an insecure image stream against _katello.example.com:5000/examplecorp-atomicimages-internal-registry-hammer_ with tag specified of _nightly_. Running _oc get is hammer -o yaml_ it is missing part of the _spec_ section:

```
spec:
  dockerImageRepository: katello.example.com:5000/examplecorp-atomicimages-internal-registry-hammer
  tags:
  - annotations: null
    generation: 3
    importPolicy:
      insecure: true
    name: nightly
```

It is missing:

```
    from:
      kind: DockerImage
      name: katello.example.com:5000/examplecorp-atomicimages-internal-registry-hammer:nightly
```
