### ISSUE TITLE
Unable to login to cockpit. Can't find username, password to use in MacOSX, kube-solo deployment.

### ISSUE THREAD

**Issue by bw2** [cockpit-project/cockpit#6549]
I can deploy the cockpit container to a local kube-solo cluster, but any username+password I try is rejected.

My ~/.kube/config file contains:
```
contexts:
- context:
    cluster: ''
    user: ''
  name: k8solo-01
```

I've also tried setting
```
kubectl config set-credentials k8solo-01 --username=admin --password=admin
```
or 
```
kubectl config set-credentials cluster-admin --username=admin --password=admin
```

My MacOSX username/password also doesn't work.
