### ISSUE TITLE
Can't login with custom user groups

### ISSUE THREAD

**Issue by Blemming** [cockpit-project/cockpit#7596]
I made a custom user group using the custom config YAML:
```
groups:
    contenteditor:
        collections:
            create: false
            delete: false
```
It shows up in the user section , but when I set a user to this group, the user can no longer log into cockpit.
I'm using cockpit Next plugged into a Mongo database. Not sure if this is a bug or I am missing something.
