### ISSUE TITLE
gke - can't login 

### ISSUE THREAD

**Issue by bw2** [cockpit-project/cockpit#9405]
I updated my google container engine kuberntes cluster to v1.8 and now can't figure out what username/password to use for cockpit.

I get 
03:13:04 Negotiate failed: Couldn't verify authentication with api: %!s(int=403)

Also, `kubectl config view` prints entries like 
```
- name: <name>
  user:
    auth-provider:
      config:
        access-token:<token>
        cmd-args: config config-helper --format=json
        cmd-path: <path>
        expiry: 2018-06-15 17:51:54
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```
but none of them have a username/password
